sudo: required
services:
  - docker

before_install:
  - docker build -t wow030/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run wow030/react-test npm test -- --coverage

after_success:
  - docker build -t wow030/multi-client ./client
  - docker build -t wow030/multi-nginx ./nginx 
  - docker build -t wow030/multi-server ./server
  - docker build -t wow030/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker log -u "$DOCKER_ID" --password--stdin
  - docker push wow030/multi-client
  - docker push wow030/multi-nginx
  - docker push wow030/multi-server
  - docker push wow030/multi-worker